apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    components.gke.io/component-name: cluster-infra-metrics
    components.gke.io/component-version: 1.32.2-gke.3
    components.gke.io/layer: addon
  creationTimestamp: "2025-07-03T14:03:05Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  managedFields:
  - apiVersion: autoscaling/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:components.gke.io/component-name: {}
          f:components.gke.io/component-version: {}
          f:components.gke.io/layer: {}
        f:labels:
          f:addonmanager.kubernetes.io/mode: {}
      f:spec:
        f:behavior:
          f:scaleDown:
            f:policies: {}
            f:stabilizationWindowSeconds: {}
          f:scaleUp:
            f:policies: {}
            f:stabilizationWindowSeconds: {}
        f:maxReplicas: {}
        f:metrics: {}
        f:minReplicas: {}
        f:scaleTargetRef:
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
    manager: kube-addon-manager
    operation: Apply
    time: "2025-07-03T14:03:05Z"
  - apiVersion: autoscaling/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"AbleToScale"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"ScalingActive"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"ScalingLimited"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:currentMetrics: {}
        f:currentReplicas: {}
        f:desiredReplicas: {}
    manager: vpa-recommender
    operation: Update
    subresource: status
    time: "2025-07-03T14:22:17Z"
  name: kube-state-metrics
  namespace: gke-managed-cim
  resourceVersion: "1751552537086351018"
  uid: e8566df8-e52e-404f-9f0b-71bb87c2c331
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 1800
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 3600
    scaleUp:
      policies:
      - periodSeconds: 300
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 900
  maxReplicas: 10
  metrics:
  - resource:
      name: memory
      target:
        averageValue: 400Mi
        type: AverageValue
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: kube-state-metrics
status:
  conditions:
  - lastTransitionTime: "2025-07-03T14:05:57Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2025-07-03T14:09:17Z"
    message: the HPA was able to successfully calculate a replica count from memory
      resource
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2025-07-03T14:05:57Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 25
        averageValue: "34430976"
        value: "34430976"
      name: memory
    type: Resource
  currentReplicas: 1
  desiredReplicas: 1
